services:
   Ecommercedb:
     container_name: EcommerceDbMonolith
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=EcommerceDb
     restart: always
     ports:
        - 5432:5432
     volumes:
        - postgres_ecommerce:/var/lib/postgresql/data/
